default_platform :mac

platform :mac do

  lane :demo_1 do
    framer(
      source_folder: "./fastlane/demo-1/screens",
      template_folder: "./fastlane/demo-1/templates",
      output_folder: "./fastlane/demo-1/final"
    )
  end

  lane :demo_2 do
    framer(
      source_folder: "./fastlane/demo-2/screens",
      template_folder: "./fastlane/demo-2/templates",
      output_folder: "./fastlane/demo-2/final"
    )
  end

  lane :android do
    framer(
      source_folder: "./fastlane/demo-3/screens",
      template_folder: "./fastlane/demo-3/template",
      output_folder: "./fastlane/demo-3/result"
    )
  end

  lane :ios do
    framer(
      source_folder: "./fastlane/demo-4/screens",
      template_folder: "./fastlane/demo-4/template",
      output_folder: "./fastlane/demo-4/result"
    )
  end

end
