lane :demo_1 do
  framer(
    source_folder: "./fastlane/demo-1/screens",
    template_folder: "./fastlane/demo-1/templates",
    output_folder: "./fastlane/demo-1/final"
  )
end

lane :demo_2 do
  framer(
    source_folder: "./fastlane/demo-2/screens",
    template_folder: "./fastlane/demo-2/templates",
    output_folder: "./fastlane/demo-2/final"
  )
end
